/**
 * World Event System
 *
 * Maintains a queue of world events generated by the World Agent.
 * Soul Agent consumes pending events to decide character reactions.
 *
 * Events are persisted so they survive restarts.
 * Each event has a unique ID to prevent duplicates (via firedIds).
 */

import type { PersistenceStore } from "./attribute-engine.js";

// ─── Types ───

export interface WorldEvent {
  id: string;
  type: "milestone" | "skill_unlock" | "holiday" | "quest" | "custom";
  title: string;
  desc: string;
  rewards?: { coins?: number; exp?: number; items?: Array<{ id: string; qty: number }> };
  createdAt: number;
  consumed: boolean;
}

interface WorldEventPersistence {
  events: WorldEvent[];
  firedIds: string[];
}

// ─── Constants ───

/** Max pending (unconsumed) events kept in queue */
const MAX_PENDING = 20;
/** Max total events kept in history (consumed + pending) */
const MAX_HISTORY = 100;
/** Auto-expire unconsumed events after 24h */
const EVENT_TTL_MS = 24 * 60 * 60_000;

// ─── System ───

export class WorldEventSystem {
  private _events: WorldEvent[] = [];
  private _firedIds: Set<string> = new Set();
  private readonly _store: PersistenceStore;

  constructor(store: PersistenceStore) {
    this._store = store;
    this._load();
  }

  /** Check if a specific event has already been fired (prevents duplicates) */
  hasFired(eventId: string): boolean {
    return this._firedIds.has(eventId);
  }

  /** Add a new world event to the queue. Returns false if duplicate. */
  addEvent(event: Omit<WorldEvent, "createdAt" | "consumed">): boolean {
    if (this._firedIds.has(event.id)) return false;

    this._events.push({
      ...event,
      createdAt: Date.now(),
      consumed: false,
    });
    this._firedIds.add(event.id);

    // Trim old consumed events if history is too large
    this._trim();
    this._save();
    return true;
  }

  /** Consume and return all pending (unconsumed) events. Marks them consumed. */
  consumePending(): WorldEvent[] {
    const now = Date.now();
    const pending = this._events.filter(
      (e) => !e.consumed && now - e.createdAt < EVENT_TTL_MS,
    );

    for (const e of pending) {
      e.consumed = true;
    }

    if (pending.length > 0) this._save();
    return pending;
  }

  /** Peek at pending events without consuming */
  peekPending(): WorldEvent[] {
    const now = Date.now();
    return this._events.filter(
      (e) => !e.consumed && now - e.createdAt < EVENT_TTL_MS,
    );
  }

  /** Get count of pending events */
  get pendingCount(): number {
    return this.peekPending().length;
  }

  /** Get all events (for debug/admin) */
  getAll(): WorldEvent[] {
    return [...this._events];
  }

  // ─── Internal ───

  private _trim(): void {
    // Remove expired unconsumed events
    const now = Date.now();
    this._events = this._events.filter(
      (e) => e.consumed || now - e.createdAt < EVENT_TTL_MS,
    );

    // Cap pending events
    const pending = this._events.filter((e) => !e.consumed);
    if (pending.length > MAX_PENDING) {
      const toRemove = pending.slice(0, pending.length - MAX_PENDING);
      for (const e of toRemove) e.consumed = true;
    }

    // Cap total history
    if (this._events.length > MAX_HISTORY) {
      this._events = this._events.slice(-MAX_HISTORY);
    }

    // Cap firedIds to prevent unbounded growth
    if (this._firedIds.size > 500) {
      const arr = [...this._firedIds];
      this._firedIds = new Set(arr.slice(-300));
    }
  }

  // ─── Persistence ───

  private _load(): void {
    const saved = this._store.load("world-events");
    if (!saved) return;
    try {
      const data = saved as unknown as WorldEventPersistence;
      if (Array.isArray(data.events)) this._events = data.events;
      if (Array.isArray(data.firedIds)) this._firedIds = new Set(data.firedIds);
    } catch { /* ignore corrupt data */ }
  }

  private _save(): void {
    this._store.save("world-events", {
      events: this._events,
      firedIds: [...this._firedIds],
    } as unknown as Record<string, unknown>);
  }
}
